# Generated by Django 2.0.3 on 2018-03-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='cropdetail',
            name='crop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crop.Crop'),
        ),
    ]
